move lat1.tex                     ..\latu
move lat2_l2.tex                  ..\latu
move lat3_l3.tex                  ..\latu
move lat4_l4.tex                  ..\latu
move lat4_m2.tex                  ..\latu
move lat5_l2onm2.tex              ..\latu
move lat5_l5.tex                  ..\latu
move lat5_m2onl2.tex              ..\latu
move lat5_m3.tex                  ..\latu
move lat5_n5.tex                  ..\latu
move lat6_l2onm2onl2.tex          ..\latu
move lat6_l2onm3.tex              ..\latu
move lat6_l2onn5.tex              ..\latu
move lat6_l3onm2.tex              ..\latu
move lat6_l4inm2.tex              ..\latu
move lat6_l6.tex                  ..\latu
move lat6_m2m2.tex                ..\latu
move lat6_m2onl3.tex              ..\latu
move lat6_m3onl2.tex              ..\latu
move lat6_m4.tex                  ..\latu
move lat6_n5onl2.tex              ..\latu
move lat6_n6.tex                  ..\latu
move lat6_o6.tex                  ..\latu
move lat6_o6bslash.tex            ..\latu
move lat6_o6slash.tex             ..\latu
move lat6_p3.tex                  ..\latu
move lat6_p3_dual.tex             ..\latu
move lat7_l2onm2m2.tex            ..\latu
move lat7_l2onm2m2_dual.tex       ..\latu
move lat7_l2onm2onl3.tex          ..\latu
move lat7_l2onm3onl2.tex          ..\latu
move lat7_l2onm4.tex              ..\latu
move lat7_l2ono6slash.tex         ..\latu
move lat7_l3ino6.tex              ..\latu
move lat7_l3ino6l.tex             ..\latu
move lat7_l3onm2onl2.tex          ..\latu
move lat7_l3onm3.tex              ..\latu
move lat7_l4m3.tex                ..\latu
move lat7_l4onm2.tex              ..\latu
move lat7_l5inm2.tex              ..\latu
move lat7_l7.tex                  ..\latu
move lat7_m2inm2.tex              ..\latu
move lat7_m2inm2_alt.tex          ..\latu
move lat7_m2inm2_dual.tex         ..\latu
move lat7_m2m2l.tex               ..\latu
move lat7_m2m2l_dual.tex          ..\latu
move lat7_m2m3.tex                ..\latu
move lat7_m2onl4.tex              ..\latu
move lat7_m2onm2.tex              ..\latu
move lat7_m3m2.tex                ..\latu
move lat7_m3onl3.tex              ..\latu
move lat7_m4onl2.tex              ..\latu
move lat7_m5.tex                  ..\latu
move lat7_o6slashonl2.tex         ..\latu
move lat7_o7slash.tex             ..\latu
move lat7_veeino6.tex             ..\latu
move lat8_2e3.tex                 ..\latu
move lat8_l2e3.tex                ..\latu
move lat8_m6.tex                  ..\latu
move lat8_o8.tex                  ..\latu
