copy c:\dan\r\xwsd\graphics\shell_coscos11.tex          . /v
copy c:\dan\r\xwsd\graphics\shell_sinsin02_pun.tex      . /v
copy c:\dan\r\xwsd\graphics\shell_coscos11ft.tex        . /v
copy c:\dan\r\xwsd\graphics\shell_rcos.tex              . /v
copy c:\dan\r\xwsd\graphics\shell_rcos_pun.tex          . /v
copy c:\dan\r\xwsd\graphics\shell_pounityz.tex          . /v
copy c:\dan\r\xwsd\graphics\shell_Fhw.tex               . /v
copy c:\dan\r\xwsd\graphics\shell_d1_phi_h.tex          . /v
copy c:\dan\r\xwsd\graphics\shell_d1_psi_g.tex          . /v
copy c:\dan\r\xwsd\graphics\shell_tent_phi_h.tex        . /v
copy c:\dan\r\xwsd\graphics\shell_tent_psi_g.tex        . /v
copy c:\dan\r\xwsd\graphics\shell_bspline_phi_h.tex     . /v
copy c:\dan\r\xwsd\graphics\shell_bspline_psi_g.tex     . /v
copy c:\dan\r\xwsd\graphics\shell_sinsin02.tex          . /v
copy c:\dan\r\xwsd\graphics\shell_sinsin02_pun.tex      . /v
copy c:\dan\r\xwsd\graphics\shell_sinsin02hn.tex        . /v
copy c:\dan\r\xwsd\graphics\shell_rsin.tex              . /v
copy c:\dan\r\xwsd\graphics\shell_rsin_pun.tex          . /v
copy c:\dan\r\xwsd\graphics\shell_rsin02hn.tex          . /v
