#-----------------------------------------------------------------------------
# Project Makefile
# Daniel J. Greenhoe
#-----------------------------------------------------------------------------
#--------------------------------------
# TARGET
#--------------------------------------
#.RECIPEPREFIX=>
#--------------------------------------
# Paths
#--------------------------------------
PATHDSP    = ../../common/math/graphics/dsp/
PATHMATH   = ../../common/math/graphics/
PATHLAT    = ../../common/math/graphics/lat/
PATHFRAMES   = ../../common/math/graphics/frames/
PATHBSPLINES = ../../common/math/graphics/bsplines/
PATHWAVE   = ../../common/wavelets/graphics/
PATHSETSTR = ../../common/math/graphics/setstr
#PATHSTO   = ../../../common/math/graphics/sto/

#--------------------------------------
# Files
#--------------------------------------
#FILE_GRP  = ../common/watercraft/ghind_djg_blue.eps  \
#            ../../../common/wavelets/morletwavelet.tex

FILE_BSPLINES = \
  b0_g.pdf              \
  b1_g.pdf              \
  b2_g.pdf              \
  b3_g.pdf              \
  b4_g.pdf              \
  n0.pdf                \
  n1.pdf                \
  n2.pdf                \
  n3.pdf                \
  n4.pdf                \
  n5.pdf                \
  n6.pdf                \
  n7.pdf                \
  n0_h.pdf              \
  n1_h.pdf              \
  n2_h.pdf              \
  n3_h.pdf              \
  n4_h.pdf              \
  n3x.pdf               \
  n0punity.pdf          \
  n1punity.pdf          \
  n2punity.pdf          \
  n0dyadic.pdf          \
  n1dyadic.pdf          \
  n2dyadic.pdf          \
  Snn_bspline.pdf       

FILE_FRAMES  =          \
  frameR2N.pdf          \
  frameR2pq.pdf         \
  mframe.pdf            \
  mframe01.pdf          \
  mframer01.pdf         \
  mframepm.pdf          

FILE_WAV = \
            bspline_pz.pdf        \
            bspline_phi_h.pdf     \
            bspline_psi_g.pdf     \
            D1_pz.pdf             \
            D2_pz.pdf             \
            D3_pz.pdf             \
            D4_pz.pdf             \
            D8_pz.pdf             \
            D12_pz.pdf            \
            D16_pz.pdf            \
            S4_pz.pdf             \
            S5_pz.pdf             \
            S6_pz.pdf             \
            S7_pz.pdf             \
            S8_pz.pdf             \
            S9_pz.pdf             \
            S10_pz.pdf            \
            S11_pz.pdf            \
            S12_pz.pdf            \
            S13_pz.pdf            \
            S14_pz.pdf            \
            S15_pz.pdf            \
            S16_pz.pdf            \
            S17_pz.pdf            \
            d1_g.pdf              \
            d1_h.pdf              \
            d1_phi.pdf            \
            d1_psi.pdf            \
            d1_phi_h.pdf          \
            d1_psi_g.pdf          \
            d2_phi_h.pdf          \
            d2_psi_g.pdf          \
            d3_phi_h.pdf          \
            d3_psi_g.pdf          \
            d4_phi_h.pdf          \
            d4_psi_g.pdf          \
            d5_phi_h.pdf          \
            d5_psi_g.pdf          \
            d6_phi_h.pdf          \
            d6_psi_g.pdf          \
            d7_phi_h.pdf          \
            d7_psi_g.pdf          \
            d8_phi_h.pdf          \
            d8_psi_g.pdf          \
            d9_phi_h.pdf          \
            d9_psi_g.pdf          \
            d10_phi_h.pdf         \
            d10_psi_g.pdf         \
            d11_phi_h.pdf         \
            d11_psi_g.pdf         \
            d12_phi_h.pdf         \
            d12_psi_g.pdf         \
            d16_phi_h.pdf         \
            d16_psi_g.pdf         \
            IntSum.pdf            \
            IntTrap.pdf           \
            linear.pdf            \
            nonti.pdf             \
            cendiff.pdf           \
            cosLcos.pdf           \
            diff.pdf              \
            ellipse12.pdf         \
            ellipse21.pdf         \
            fnctsq.pdf            \
            fnct123ab.pdf         \
            fnct123ab123.pdf      \
            fnct123le123.pdf      \
            iir2n.pdf             \
            iir1pole.pdf          \
            dfI_order2_156.pdf    \
            dfI_order2_fir.pdf    \
            pz_allpass.pdf        \
            pz_minphase.pdf       \
            pz_minphase_inv.pdf   \
            pz_stable.pdf         \
            pz_pole00.pdf         \
            pz_realcoefs.pdf      \
            pz_realcoefs_11.pdf   \
            pz_unstable.pdf       \
            pz_unstable2.pdf      \
            pz_unall.pdf          \
            oplat.pdf             \
            ziir2.pdf             \
            Dp_pz.pdf             \
            haar0_sin_t.pdf       \
            haar0_sin_a.pdf       \
            haar1_sin_t.pdf       \
            haar1_sin_a.pdf       \
            haar2_sin_t.pdf       \
            haar2_sin_a.pdf       \
            latwav.pdf            \
            lpfwc.pdf             \
            hpfwc.pdf             \
            mexhatwavelet.pdf     \
            morletwavelet.pdf     \
            s4_phi_h.pdf          \
            s4_psi_g.pdf          \
            s8_phi_h.pdf          \
            s8_psi_g.pdf          \
            s12_phi_h.pdf          \
            s12_psi_g.pdf          \
            s16_phi_h.pdf          \
            s16_psi_g.pdf          \
            tent_phi_h.pdf        \
            tent_psi_g.pdf

GRP_SETSTR = \
  lattopxy.pdf             

FILE_GRP  =             \
  baslat_cheby.pdf      \
  baslat_cose.pdf       \
  baslat_cosh.pdf       \
  baslat_haar.pdf       \
  baslat_h3.pdf         \
  baslat_d1.pdf         \
  baslat_d2.pdf         \
  dirichlet1.pdf        \
  dirichlet5.pdf        \
  dirichlet10.pdf       \
  dirichlet20.pdf       \
  fstep.pdf             \
  opTrn.pdf             \
  opDil.pdf             \
  latmn.pdf             \
  latmra.pdf            \
  latp_1235711.pdf      \
  latp_VW.pdf           \
  latp_hg.pdf           \
  latp_pp.pdf           \
  lattopxy.pdf          \
  pulse.pdf             \
  pulse2.pdf            \
  pz_minphase.pdf       \
  pz_realcoefs.pdf      \
  pz_stable.pdf         \
  pz_unstable.pdf       \
  sin_pi_t.pdf          \
  hn1.pdf               \
  lat6_plat_xyzv10.pdf  \
  cencubs.pdf           \
  cencubs_pun.pdf       \
  coscos11.pdf          \
  coscos11ft.pdf        \
  pounityz.pdf          \
  pulse03.pdf           \
  pulse_pun.pdf         \
  Fpulse.pdf            \
  pulseabc.pdf          \
  pulseabcft.pdf        \
  rcos.pdf              \
  rcos_pun.pdf          \
  rsin.pdf              \
  rsin_pun.pdf          \
  rsin02hn.pdf          \
  sinsin02.pdf          \
  sinsin02_pun.pdf      \
  sinsin02hn.pdf        \
  tentfx.pdf            \
  tent_pun.pdf          \
  tent012.pdf           \
  Ftent012.pdf          \
  FN2.pdf               \
  DT_tentfx.pdf         \
  TD_tentfx.pdf         \
  triangleabc.pdf       \
  triangleabcft.pdf     \
  unitcircle.pdf        \
  vecres.pdf            \
  Fhw.pdf               

FILE_STY  = ../../common/sty/wavelets.sty \
            ../../common/sty/math.sty     \
            ../../common/sty/dan.sty      \
            ../../common/sty/defaults.sty \
            ../../common/sty/fonts.sty    \
            ../../common/sty/packages.sty \
            ../../common/sty/xsd.sty       \
            ../../common/sty/language.sty

#--------------------------------------
# Programs
#--------------------------------------
PRG_TYPESET = xelatex.exe
#PRG_XDV2PDF = xdvipdfmx.exe

#--------------------------------------
# master build control
#--------------------------------------
top: $(FILE_FRAMES) $(FILE_GRP) $(GRP_SETSTR) $(FILE_WAV) $(FILE_BSPLINES) $(FILE_STY)
	@echo Done ... basis/graphics pdfs are ready!
#  echo % >> mainx.idx # make sure general   index file exists

#--------------------------------------
# implicit build control
#--------------------------------------
#[../../../common/math/graphics].tex.pdf:
#{[c:/dan/r/common/math/graphics/]}.tex.pdf:
#..\..\..\common\math\graphics\%.tex%.pdf:
#$&.pdf: ../../../common/math/graphics/$&.tex
#[$(PATHSRC)].tex.pdf:
#{../}.tex.pdf:

{$(PATHMATH)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHBSPLINES)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHLAT)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHFRAMES)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHSETSTR)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHDSP)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHWAVE)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

#{$(PATHSTO)}.tex.pdf:
#	$(PRG_TYPESET) shell_$&.tex
#	copy /V/Y shell_$&.pdf $&.pdf
#	del shell_$&.pdf

.pdf.eps:
	pdftops -eps $&.pdf $&.eps
	#pdftops -eps -noembt1 -noembtt $&.pdf $&.eps
	#pdftops -eps -noembt1 -noembtt -noembcidps -noembcidtt $&.pdf $&.eps

#--------------------------------------
# explicit build control
#--------------------------------------
#opTrn.pdf: ../../../common/math/graphics/opTrn.tex 
#	$(PRG_TYPESET) shell_$&.tex
#	copy /V/Y shell_$&.pdf $&.pdf
#	del shell_$&.pdf
#
#latmn.pdf: ../../../common/wavelets/graphics/latmn.tex 
#	$(PRG_TYPESET) shell_latmn.tex
#	copy /V/Y shell_latmn.pdf latmn.pdf
#	del shell_latmn.pdf

#--------------------------------------
# commands
#--------------------------------------
clean:
 #del *.eps
  del *.aux
  del *.log
  del *.out

make scrub:
  make clean
  del *.pdf

