#-----------------------------------------------------------------------------
# Project Makefile
# Daniel J. Greenhoe
#-----------------------------------------------------------------------------
#--------------------------------------
# TARGET
#--------------------------------------
#.RECIPEPREFIX=>
#--------------------------------------
# Paths
#--------------------------------------
PATHARGMIN   = ../argmin/
PATHBALLS    = ../balls/
PATHDATA     = ../data/
PATHDSP      = ../dsp/
PATHFRAME    = ../frames/
PATHMATH     = ../
PATHBSPLINES = ../bsplines/
PATHMETRIC   = ../metric/
PATHOMS      = ../oms/
PATHPROB     = ../prob/
PATHVENN     = ../venn/
PATHSETSTR   = ../setstr/
PATHSYSTEM   = ../system/
PATHWAVE     = ../wavelets/
PATHHISTORY  = ../history/
PATHCC       = ../../common/graphics/cc/
PATHOSETU    = ../osetu/
PATHLAT      = ../lat/
PATHLATU     = ../latu/
PATHLATOC    = ../latoc/
PATHNEG      = ../neg/
PATHOCS      = ../ocs/
PATHOCSRV    = ../ocsrv/
PATHOSET     = ../oset/
PATHLOGIC    = ../
PATHFUZZY    = ../fuzzy/
PATHSETOPS   = ../setops/
PATHSTO      = ../sto/
PATHSYMSEQ   = ../symseq/

#--------------------------------------
# Files
#--------------------------------------
FILE_CC =                \
  ccby40djg.pdf          \
  ccbyncnd40djg.pdf      \
  ccby40.pdf

#  12000_2428.pdf         \

FILE_GRP  =              \
  latnegations.pdf       \
  argmin_xx-2x2.pdf      \
  bijective_x4y4.pdf     \
  dmetricdnatoc.pdf      \
  earc_def.pdf           \
  ellipse12.pdf          \
  ellipse21.pdf          \
  ex_convex.pdf          \
  function_x4y4.pdf      \
  gspRZ.pdf              \
  hanninghp50.pdf        \
  hanninglp16.pdf        \
  hanninglp50.pdf        \
  injective_x4y4.pdf     \
  2xyfnct1.pdf           \
  2xyfnct2.pdf           \
  2xynotfnct1.pdf        \
  2xynotfnct2.pdf        \
  dirichlet1.pdf        \
  dirichlet5.pdf        \
  dirichlet10.pdf       \
  dirichlet20.pdf       \
  fnct123ab.pdf         \
  fnct123ab123.pdf      \
  fnct123le123.pdf      \
  fstep.pdf             \
  pulse.pdf             \
  pulse2.pdf            \
  hn1.pdf               \
  lat6_plat_xyzv10.pdf  \
  cencubs.pdf           \
  cencubs_pun.pdf       \
  coscos11.pdf          \
  coscos11ft.pdf        \
  notablemath.pdf       \
  pounityz.pdf          \
  pulse03.pdf           \
  pulse_pun.pdf         \
  Fpulse.pdf            \
  pulseabc.pdf          \
  pulseabcft.pdf        \
  pz_minphase.pdf       \
  pz_realcoefs.pdf      \
  pz_stable.pdf         \
  pz_unstable.pdf       \
  r3_projection.pdf     \
  rcos.pdf              \
  rcos_pun.pdf          \
  rsin.pdf              \
  rsin_pun.pdf          \
  rsin02hn.pdf          \
  sinsin02.pdf          \
  sinsin02_pun.pdf      \
  sinsin02hn.pdf        \
  spaces.pdf            \
  tentfx.pdf            \
  tent_pun.pdf          \
  tent012.pdf           \
  Ftent012.pdf          \
  FN2.pdf               \
  DT_tentfx.pdf         \
  TD_tentfx.pdf         \
  triangleabc.pdf       \
  triangleabcft.pdf     \
  unitcircle.pdf        \
  unitcircle_RecipricolConjugate.pdf \
  unitcircle_roots1.pdf \
  unitcircle_roots2.pdf \
  unitcircle_roots3.pdf \
  unitcircle_roots4.pdf \
  unitcircle_roots5.pdf \
  vecres.pdf            \
  Fhw.pdf

GRP_BASIS = \
	baslat_cosh.pdf                        \
	baslat_cose.pdf                        \
	baslat_cheby.pdf                       \
	baslat_d1.pdf                          \
	baslat_d2.pdf                          \
	baslat_h3.pdf                          \
	baslat_haar.pdf                        \
	baslat_h3.pdf                          \
	baslat_d1_yellow.pdf                   \
	baslat_d2_yellow.pdf                   \
	baslat_h3_yellow.pdf                   \
	baslat_cheby_yellow.pdf                \
	baslat_cose_yellow.pdf                 \
	baslat_cosh_yellow.pdf                 \
	haar0_sin_t.pdf                        \
	haar0_sin_a.pdf                        \
	haar1_sin_t.pdf                        \
	haar1_sin_a.pdf                        \
	haar2_sin_t.pdf                        \
	haar2_sin_a.pdf                        \
	latmn.pdf                              \
	latmra.pdf                             \
	latwav.pdf                             \
	opTrn.pdf                              \
	opDil.pdf

BSPLINES = \
	b0_g.pdf                               \
	b1_g.pdf                               \
	b2_g.pdf                               \
	b3_g.pdf                               \
	b4_g.pdf

GRP_DATA =                     \
  cagefree-ratios.pdf          \
  dji30_20171006-20181004.pdf  \
  egg-production.pdf           \
  earthquake_kapi_20180928.pdf \
  global-temp.pdf              \
  sunspots.pdf                 \
  sunspots_acf.pdf             \
  sunspots_coefs_acf.pdf       \
  sunspots_dft_basis.pdf       \
  sunspots_dft_coefs_Real.pdf  \
  sunspots_dft_coefs_Imag.pdf  \
  sunspots_dft_acf.pdf         \
  sunspots_dft_syn.pdf         \
  sunspots_eigen.pdf           \
  sunspots_eigen_coefs.pdf     \
  sunspots_eigen_syn.pdf       \
  sunspots_psd.pdf             \
  sunspots_walsh_0.pdf         \
  sunspots_walsh_1.pdf         \
  sunspots_walsh_2.pdf         \
  sunspots_walsh_3.pdf         \
  sunspots_walsh_4.pdf         \
  sunspots_walsh_2047.pdf      \
  sunspots_walsh_coefs.pdf     \
  sunspots_1749-2004.pdf       \
  sunspots_welchPSD_4segs.pdf

GRP_DICE =                                     \
	pdice_xy.pdf                               \
	dicetol6.pdf                               \
	pairdice.pdf                               \
	udicetol6.pdf                              \
	fairdieXO6.pdf                             \
	fairdieXO6c.pdf                            \
	fairdieXRYZ.pdf                            \
	m2tol4phi.pdf                              \
	seq_12000_2428.pdf                         \
	seq_hprect16.pdf                           \
	seq_lprect16.pdf                           \
	seq_shaar16.pdf                            \
	seq_shaar8.pdf                             \
	seq_whaar16.pdf                            \
	seq_whaar8.pdf                             \
	seq_whaar9.pdf                             \
	Zline.pdf                                  \
	die_realline.pdf                           \
	fspin_5eed_16002_histo.pdf                 \
	fdie_5eed_16000_auto.pdf                   \
	fdie_5eed_16000_histo.pdf                  \
	fdie_5eed_16002_auto.pdf                   \
	fdie_5eed_16002_histo.pdf                  \
	fdie_5eed_16ones_R1_histo.pdf              \
	fdie_5eed_16ones_r6ae.pdf                  \
	fdie_5eed_16ones_R6_histo.pdf              \
	fdie_5eed_51_seq.pdf                       \
	rdie_16hp.pdf                              \
	rdie_16ones.pdf                            \
	rdie_3d_larcball.pdf                       \
	rdie_50hp.pdf                              \
	rdie_5eed_16000_16ones_auto.pdf            \
	rdie_5eed_16000_16ones_R3_auto.pdf         \
	rdie_5eed_16000_auto.pdf                   \
	rdie_5eed_16000_histo.pdf                  \
	rdie_5eed_16002_auto.pdf                   \
	rdie_5eed_16002_histo.pdf                  \
	rdie_5eed_16002_R1_rect_auto.pdf           \
	rdie_5eed_16002_R1_rect_histo.pdf          \
	rdie_5eed_16002_R3_rect_larc_auto.pdf      \
	rdie_5eed_16002_R3_rect_larc_histo.pdf     \
	rdie_5eed_16ones.pdf                       \
	rdie_5eed_16ones_histo.pdf                 \
	rdie_5eed_16ones_histo_euclid.pdf          \
	rdie_5eed_16ones_histo_larc.pdf            \
	rdie_5eed_16ones_histo_R1.pdf              \
	rdie_5eed_16ones_r3euclid.pdf              \
	rdie_5eed_16ones_r3larc.pdf                \
	rdie_r3met.pdf                             \
	rdie_wxyz.pdf                              \
	wdietoO6c.pdf                              \
	wdieXO6YO6c.pdf                            \
	wdieXR.pdf                                 \
	wdie_max.pdf                               \
	wdie_5eed_160000_down50_histo.pdf                  \
	wdie_5eed_160000_hanning_down50_R1_histo.pdf       \
	wdie_5eed_160000_hanning_down50_R3larc_histo.pdf   \
	wdie_5eed_160000_recthp_down50_R3larc_histo.pdf    \
	wdie_5eed_16000_auto.pdf                           \
	wdie_5eed_16000_histo.pdf                          \
	wdie_5eed_16002_auto.pdf                           \
	wdie_5eed_16002_histo.pdf                          \
	wdie_5eed_5555_75_5_16hp.pdf                       \
	wdie_5eed_5555_75_5_16hp_r3larc.pdf                \
	wdie_5eed_5555_75_5_16hp_r3larc_16down.pdf         \
	wdie_5eed_hanninghp_R1.pdf                         \
	wdie_5eed_hanninghp_R1_histo.pdf                   \
	wdie_5eed_hanninghp_R3_euclid.pdf                  \
	wdie_5eed_hanninghp_R3_euclid_histo.pdf            \
	wdie_5eed_hanninghp_R3_larc.pdf                    \
	wdie_5eed_hanninghp_R3_larc_histo.pdf              \
	wdie_5eed_recthp_R1.pdf                            \
	wdie_5eed_recthp_R1_histo.pdf                      \
	wdie_5eed_recthp_R3_euclid.pdf                     \
	wdie_5eed_recthp_R3_euclid_histo.pdf               \
	wdie_5eed_recthp_R3_larc.pdf                       \
	wdie_5eed_recthp_R3_larc_histo.pdf                 \
	spinner_5eed.pdf                                   \
	spinner_5eed_16ones.pdf                            \
	spinner_r2.pdf                                     \
	spin_5eed.pdf                                      \
	spin_5eed_16000_auto.pdf                           \
	spin_5eed_16000_histo.pdf                          \
	spin_5eed_16002_auto.pdf                           \
	spin_5eed_16002_histo.pdf                          \
	spin_5eed_16ones_histo_larc.pdf                    \
	spin_5eed_16ones_histo_R1.pdf                      \
	spin_5eed_16ones_r2larc.pdf                        \
	surjective_x4y4.pdf                                \
	wspin_5eed_16000_auto.pdf                          \
	wspin_5eed_16000_histo.pdf                         \
	wspin_5eed_16002_auto.pdf                          \
	wspin_5eed_16002_histo.pdf                         \
	wspin_5eed_5555_75_5.pdf

# rdie_larcball.pdf                          \
# dna_51_seq.tex               \
# dna_5eed_16002_auto.pdf      \
# spinner_5eed_16000_auto.pdf                        \
# spinner_5eed_16002_auto.pdf                        \

GRP_DNA =                      \
  dna_5eed_16000_histo.pdf     \
  dna_5eed_51_seq.pdf          \
  dna_ebola.pdf                \
  dna_ebola_51_seq.pdf         \
  dna_ebola_auto.pdf           \
  dna_ebola_histo.pdf          \
  dna_SARSCoV2_51_seq.pdf      \
  dna_mpbacterium_51_seq.pdf   \
  dna_mpbacterium_auto.pdf     \
  dna_mpbacterium_histo.pdf    \
  dna_papaya1446_51_seq.pdf    \
  dna_papaya1446_auto.pdf      \
  dna_papaya1446_histo.pdf     \
  dna_sars.pdf                 \
  dna_sars_51_seq.pdf          \
  dna_sars_auto.pdf            \
  dna_sars_histo.pdf           \
  dna_5eed_16000_auto.pdf      \
  dna.pdf                      \
  dnatoc.pdf                   \
  dnatol4.pdf                  \
  dnaXO4c.pdf                  \
  dna_Rmax.pdf

GRP_DSP  = \
	cendiff.pdf                            \
	diff.pdf                               \
	IntSum.pdf                             \
	IntTrap.pdf                            \
	sinc.pdf                               \
	sinsin02.pdf                           \
	sinsin02hn.pdf                         \
	sinsin02_pun.pdf                       \
	sin_pi_t.pdf                           \
	dfI_order1_abc.pdf                     \
	dfI_order1_lpf2pi3.pdf                 \
	dfI_order2_156.pdf                     \
	dfI_order2_fir.pdf                     \
	dfI_order2_156.pdf                     \
	dfII_order1_abc.pdf                    \
	D4_pz.pdf                              \
	S4_pz.pdf                              \
	d4_phi_h.pdf                           \
	s4_phi_h.pdf                           \
	hanninglp50.pdf                        \
	hpfwc.pdf                              \
	lpfwc.pdf                              \
	iir2n.pdf                              \
	iir2rphi.pdf                           \
	iir1pole.pdf                           \
	pz_allpass.pdf                         \
	pz_minphase.pdf                        \
	pz_minphase_inv.pdf                    \
	pz_stable.pdf                          \
	pz_pole00.pdf                          \
	pz_realcoefs.pdf                       \
	pz_realcoefs_11.pdf                    \
	pz_unstable.pdf                        \
	pz_unstable2.pdf                       \
	pz_unall.pdf                           \
	rectangular_1N.pdf                     \
	samplat.pdf                            \
	sin_pi_t_sampled.pdf                   \
	sinclat.pdf                            \
	unitcircle.pdf                         \
	vecres.pdf                             \
	ziir2.pdf

GRP_FRAMES  = \
	frameR2N.pdf                           \
	frameR2pq.pdf                          \
	mframe.pdf                             \
	mframe01.pdf                           \
	mframer01.pdf                          \
	mframepm.pdf                           
                                           
GRP_FUZZY =                                \
	young.pdf                              \
	lat2_L2_fuzzy_msf.pdf                  \
	lat3_L3_fuzzy_msf2.pdf                 \
	lat3_L3_fuzzy_heyting3_msf.pdf         \
	lat4_m2_minmax_msf.pdf                 \
	lat4_m2_lukas_msf.pdf                  \
	lat6_o6_minmax_msf.pdf                 \
	lat6_o6_lukas_msf.pdf                  \
	lat12_l2e3x_minmax_msf.pdf             \
	lat4_m2_fuzzylat_msf.pdf               \
	lat6_o6_fuzzylat_msf.pdf               \
	lat8_l2e3_fuzzylat_msf.pdf             \
	lat6_o6_10xy-x.pdf                     
                                           
GRP_LARC =                                 \
	larc_ball(0_0_-1).pdf                  \
	larc_ball(0_0_-10).pdf                 \
	larc_ball(0_0_-2).pdf                  \
	larc_ball(0_0_-3).pdf                  \
	larc_ball(0_0_-5).pdf                  \
	larc_ball(0_0_0).pdf                   \
	larc_ball(0_0_1).pdf                   \
	larc_ball(1_1_1).pdf                   \
	limrp0.pdf                             \
	limrp0Rpq.pdf                          
                                           
GRP_MATH = \                               
	r3subspaces_xyzxcyczc.pdf              \
	ballinball.pdf                         \
	m2tol4.pdf                             \
	m3ton5.pdf                             \
	n5ton5.pdf                             \
	r3subspaces_xy.pdf                     \
	orderingsxyz.pdf                       \
	pulseabc.pdf                           \
	pulseabcft.pdf                         \
	triangleabc.pdf                        \
	triangleabcft.pdf                      \
	lat2xyz_antichains.pdf                 \
	m3m3_antichain_abcpqr.pdf

#gsizewdie_max.pdf


OCS = \
	gsp_markov2.pdf                        \
	rline_argminmax_11312.pdf              \
	rline_argminmax_11312a.pdf             \
	wdie_xy.pdf                            \
	lcg7x1m9_XYZ.pdf                       \
	lcg7x1m9_max.pdf                       \
	lcg7x1m9_seqorder.pdf                  \
	lcg7x1m9_dgraph.pdf                    \
	dqpsk.pdf                              \
	network.pdf                            \
	latlatringsxyz.pdf                     \
	wring5.pdf                             \
	dartstarget.pdf                        \
	ocsdarts.pdf                           \
	pspinner.pdf                           \
	pspinner_xy.pdf                        \
	spinner6tol6.pdf                       \
	spinnerXO6c.pdf                        \
	spinnerXO6Ycircle.pdf                  \
	spinner_x2x.pdf                        \
	wspinner.pdf                           \
	wspinnermax.pdf                        \
	wspinner_Rmax.pdf                      \
	ocsarchery.pdf                         \
	ocsrv_spinner_xy.pdf                   \
	ocs_dna.pdf                            \
	ocs_dnan.pdf                           \
	ocs_fdie.pdf                           \
	ocs_rdie.pdf                           \
	ocs_spinner.pdf                        \
	ocs_spinner_121141.pdf                 \
	ocs_wagon.pdf                          \
	ocs_wagon_121141.pdf                   \
	ocs_wdie.pdf                           \
	ocs_wdie_121141.pdf                    \
	ocs_wrdie.pdf                          \
	ocs_wrdie_e75.pdf                      \
	pEocsE_max.pdf

#	ocsrv_xy.pdf                           \

OMS = \
	oms_dna.pdf                            \
	oms_fdie.pdf                           \
	oms_l2e3_235.pdf                       \
	oms_rdie.pdf                           \
	oms_spinner.pdf                        \
	oms_wring5shortd.pdf                   \
	wring5shortd.pdf                       \
	wring5short.pdf                        \
	archerytarget.pdf                      \
	ring6.pdf                              \
	discretemetric6.pdf                    \
	Zline.pdf                              \
	realline.pdf                           \
	Cplane.pdf

GRP_PDS = \
	ae_ball(00_00_05).pdf                  \
	ballinopen.pdf                         \
	larc_ball(00_00_05).pdf                \
	larc_def.pdf                           \
	larc_earc_compare.pdf                  \
	larc_euclid_compare.pdf                \
	larc_hmg.pdf                           \
	larc_metex.pdf                         \
	larc_pq.pdf                            \
	larc_R2_balls.pdf                      \
	larc_ti.pdf                            \
	larc_trieq.pdf                         \
	mca_R2_balls.pdf                       \
	mpf_ascaled.pdf                        \
	mpf_bounded.pdf                        \
	mpf_discrete.pdf                       \
	mpf_snowflake.pdf                      \
	mpf_truncated.pdf                      \
	mpf_x1x2.pdf                           \
	mpf_0121.pdf                           \
	mpf_11x1.pdf                           \
	mpf_x11x1.pdf                          \
	trirel_sigmap.pdf

# atanmet.pdf

GRP_PROB = \
	latestimation.pdf                      \
	estimation_techniques.pdf              \
	lat3_L3_1x0_-0-x-1_prob.pdf            \
	lat4_m2_psE_coin.pdf                   \
	lat4_m2_boa_prob.pdf                   \
	lat4_m2_prob_die.pdf                   \
	lat6_o6_prob_10adbc.pdf                \
	lat8_l2e3_prob_coin.pdf                \
	lat8_l2e3_prob_die.pdf                 \
	pdf_dicesum_bluered.pdf                \
	pdf_fairdie_blue.pdf                   \
	pdf_fairdie_red.pdf

GRP_LATP =                                 \
	latp.pdf                               \
	latp_1235711.pdf                       \
	latp_VW.pdf                            \
	latp_hg.pdf                            \
	latp_pp.pdf                            \
	latp_bortho_L5.pdf                     \
	latp_cosets5Z.pdf                      \
	latp_fuzzy.pdf                         \
	latp_gsp_AorT.pdf                      \
	latp_gsp_atcgx.pdf                     \
	latp_prob.pdf                          \
	lat4_m2_latoc_r.pdf                    \
	lat4_m2_qb.pdf                         \
	lat6_p3.pdf                            \
	lat6_o6_pq.pdf                         \
	lat6_o6_prab.pdf                       \
	lat6_p3_dual.pdf                       \
	lat6_p3_xyzv01.pdf                     \
	lat7_l4m3.pdf                          \
	lat7_l3ino6l.pdf                       \
	lat7_m2m2l.pdf                         \
	lat7_m2m2l_dual.pdf                    \
	lat7_m2inm2_dual.pdf                   \
	lat8_l2e3_latoc_paq.pdf                \
	lat8_l2e3_latoc_pbr.pdf                \
	lat8_l2e3_latoc_pcs.pdf                \
	lat8_l2e3_latoc_pqs.pdf                \
	lat8_l2e3_latoc_prs.pdf                \
	lat8_l2e3_latoc_qbs.pdf                \
	lat8_l2e3_latoc_qcr.pdf                \
	lat8_l2e3_latoc_qrs.pdf                \
	lat8_l2e3_latoc_ras.pdf                \
	lat8_l2e3_pqrabc.pdf                   \
	lat16_l2e4_latoc_pqrs_fec.pdf          \
	lat16_l2e4_latoc_pqsi.pdf              \
	lat16_l2e4_latoc_pqtf.pdf              \
	lat16_l2e4_latoc_qrst.pdf

#	lat6_o6_1=-0_a=-d_b=-c_c=-b_d=-a_0=-1_prob.pdf \
#	lat7_m2inm2l.pdf


GRP_LATU = \
	lat1.pdf                               \
	lat2_l2.pdf                            \
	lat3_l3.pdf                            \
	lat4_l4.pdf                            \
	lat4_m2.pdf                            \
	lat5_l5.pdf                            \
	lat5_m3.pdf                            \
	lat5_n5.pdf                            \
	lat5_l2onm2.pdf                        \
	lat5_m2onl2.pdf                        \
	lat5_m3_tall.pdf                       \
	lat6_m4.pdf                            \
	lat6_l4inm2.pdf                        \
	lat6_o6.pdf                            \
	lat6_o6slash.pdf                       \
	lat6_n6.pdf                            \
	lat6_o6bslash.pdf                      \
	lat6_l3onm2.pdf                        \
	lat6_m2onl3.pdf                        \
	lat6_l2onm2onl2.pdf                    \
	lat6_l2onn5.pdf                        \
	lat6_n5onl2.pdf                        \
	lat6_l2onm3.pdf                        \
	lat6_m3onl2.pdf                        \
	lat6_l6.pdf                            \
	lat6_m2m2.pdf                          \
	lat7_m2onm2.pdf                        \
	lat7_l2ono6slash.pdf                   \
	lat7_o6slashonl2.pdf                   \
	lat7_l4onm2.pdf                        \
	lat7_l3onm2onl2.pdf                    \
	lat7_l2onm2onl3.pdf                    \
	lat7_m2onl4.pdf                        \
	lat7_l7.pdf                            \
	lat7_m5.pdf                            \
	lat7_m3m2.pdf                          \
	lat7_m2m3.pdf                          \
	lat7_l2onm4.pdf                        \
	lat7_m4onl2.pdf                        \
	lat7_l3onm3.pdf                        \
	lat7_m3onl3.pdf                        \
	lat7_l2onm3onl2.pdf                    \
	lat7_o7slash.pdf                       \
	lat7_m2inn5.pdf                        \
	lat7_l3ino6.pdf                        \
	lat7_l3ino6slash.pdf                   \
	lat7_o7.pdf                            \
	lat7_l4l5l4.pdf                        \
	lat7_l3l5l5.pdf                        \
	lat7_l5inm2.pdf                        \
	lat7_l2onn5onl2.pdf                    \
	lat7_l2onm3onl2.pdf                    \
	lat7_l6l3.pdf                          \
	lat7_n7.pdf                            \
	lat7_l7.pdf                            \
	lat7_m3n5.pdf                          \
	lat7_m2inm2.pdf                        \
	lat7_m2inm2_alt.pdf                    \
	lat7_m2m2m2.pdf                        \
	lat7_m3m2.pdf                          \
	lat7_m2o6.pdf                          \
	lat7_n5m2.pdf                          \
	lat7_n6m2.pdf                          \
	lat7_n6n5.pdf                          \
	lat7_l2onp3.pdf                        \
	lat7_l2onp3dual.pdf                    \
	lat7_l3onn5.pdf                        \
	lat7_l2ono6.pdf                        \
	lat7_l2onl4inm2.pdf                    \
	lat7_l2onn6.pdf                        \
	lat8_l2e3.pdf                          \
	lat8_l2e3_psetx.pdf                    \
	lat8_l2e3_fuzzylat_msf.pdf             \
	lat12_mo2x2.pdf

GRP_LAT =                               \
	123le12.pdf                         \
	lat4_l4_1234.pdf                    \
	lat4_m2_1xy0.pdf                    \
	lat4_m2_topxy.pdf                   \
	lat5_n5_0abp1.pdf                   \
	lat5_n5_xyz.pdf                     \
	lat5_n5_abz.pdf                     \
	lat5_pentbslash_1xyz0.pdf           \
	lat5_l2onm2_1xyz0.pdf               \
	lat5_m3_pqr.pdf                     \
	lat5_m3_xyz.pdf                     \
	lat6_o6slash_123.pdf                \
	lat6_l4inm2_xyab01.pdf              \
	lat6_primo_xyza01.pdf               \
	lat6_primo_dual_xyza01.pdf          \
	lat6_o6_10xy-x.pdf                  \
	lat6_o6_dslash_1abxy0.pdf           \
	lat6_o6bslash_xyab01.pdf            \
	lat6_o6_xyab01.pdf                  \
	lat6_plat_P12345.pdf                \
	lat6_plat_V12345.pdf                \
	lat6_o6_pqab01.pdf                  \
	lat6_primo_pqra01.pdf               \
	lat7_veeino6_xyzab01.pdf            \
	lat7_wedgeino6_xyabc01.pdf          \
	lat8_2e3_setxyz.pdf                 \
	lat8_2e3_setxyzd.pdf                \
	lat8_2e3_set235.pdf                 \
	lat8_l2e3_abc_h.pdf                 \
	lat6_o6_acpr_h.pdf

GRP_BOOLEAN =                           \
	lat2_l2_setx.pdf                    \
	lat4_l2e2_setxy.pdf                 \
	lat4_m2_setxy.pdf                   \
	lat8_2e3_setxyz.pdf

GRP_LOGIC = \
  logic_BN4_tbnf.pdf                    \
  logic_L2_tf.pdf                       \
  logic_L3_tnf.pdf                      \
  logic_L3_tnf_fft.pdf                  \
  logic_L5_tpnmf.pdf                    \
  logic_M2_tmnf.pdf                     \
  logic_O6slash_tpqmnf.pdf              \
  lat6_o6_negor.pdf

GRP_NEG =                               \
	lat2_L2_10_-0-1.pdf                 \
	lat3_L3_1-1_x-x_0-0.pdf             \
	lat3_L3_1-0_x-1_0-x.pdf             \
	lat3_L3_1-x_x-0_0-1.pdf             \
	lat3_L3_1_a-0_0-1-a.pdf             \
	lat6_o6_1-0_a-b_b-a_c-d_d-c_0-1.pdf \
	lat3_L3_1x0_-0-1-x.pdf              \
	lat3_L3_1x0_-1x0.pdf                \
	lat3_L3_1-0-a_a_0-1.pdf             \
	lat3_L3_1-a-0_a-1_0.pdf             \
	lat3_L3_1x0_-0-x-1.pdf              \
	lat3_L3_1-0_a_0-1-x.pdf             \
	lat4_m2_1-0_a_b-b_0-1-a.pdf         \
	lat4_m2_a-b_b-a.pdf                 \
	lat4_bn4_a-a_b-b.pdf                \
	lat4_m2_1-0_a_b-b_0-1-a.pdf         \
	lat3_L3_1-0_a_0-1-x.pdf             \
	lat3_L3_1x0_-0-x-1.pdf              \
	lat6_n6_0abcp1.pdf                  \
	lat5_n5_0acp1.pdf                   \
	lat6_o6_negor.pdf                   \
	lat5_m3_negdm.pdf                   \
	lat5_m3_negkl.pdf                   \
	lat6_o6_negdm.pdf                   \
	lat6_o6_negor.pdf                   \
	lat6_o6slash_nonantitone.pdf        \
	lat6_o6slash_kleene.pdf             \
	lat8_l2e3_abc_dm.pdf                \
	lat8_l2e3_abc_ortho.pdf

GRP_LATOC =                             \
	lat1_01.pdf                         \
	lat2_l2_01.pdf                      \
	lat4_m2_latoc_p.pdf                 \
	lat4_m2_latoc_q.pdf                 \
	lat6_o6_latoc_pq.pdf                \
	lat6_o6_xy.pdf                      \
	lat6_m4_wxyz.pdf                    \
	lat6_mo2_xy.pdf                     \
	lat6_o6_center.pdf                  \
	lat8_o8_xyp.pdf                     \
	lat8_2e3m2_bwaoc.pdf                \
	lat8_2e3m2_xyzoc.pdf                \
	lat8_l3l4l4l3_xypoc.pdf             \
	latoc2xyz_center.pdf                \
	lat10_n5n5oc_xyp.pdf                \
	lat10_m4m4oc_wxyz.pdf               \
	lat10_o8m2_xypqoc.pdf               \
	lat10_hsum_pxyz.pdf                 \
	latocdil7_abxyzcd.pdf               \
	lat8_m6_xyzoc.pdf                   \
	lat8_l2e3_latoc_pqr.pdf             \
	lat10_n5n5oc_xyzp_center.pdf        \
	lat10_o8m2_center_xypqoc.pdf        \
	lat16_l2e4_latoc_pqrs.pdf           \
	lat32_l2e5_latoc_pqrst.pdf

GRP_NIL =                               \
	m3m3_antichain.pdf                  \
	lat3_L3_psetx.pdf                   \
	lat3_L3_setind.pdf                  \
	lat6_o6_psetx.pdf                   \
	lat6_o6_setind.pdf                  \
	lat8_l2e3_setind.pdf                \
	lat6_o6_setind.pdf                  \
	lat5_m3_xyz_dot.pdf

GRP_OSET =                              \
	oset3_wedge_ab1.pdf                 \
	oset6_o6x_abcd01.pdf                \
	oset3_wedge.pdf                     \
	oset4_Nref.pdf                      \
	oset7_wedge_oplus_Nref.pdf          \
	oset12_wedge_times_Nref.pdf         \
	oset12_wedge_otimes_Nref.pdf

GRP_POUNITY =                           \
	coscos11.pdf                        \
	sinsin02_pun.pdf                    \
	coscos11ft.pdf                      \
	rcos.pdf                            \
	rcos_pun.pdf                        \
	pounityz.pdf                        \
	Fhw.pdf                             \
	d1_phi_h.pdf                        \
	d1_psi_g.pdf                        \
	tent_phi_h.pdf                      \
	tent_psi_g.pdf                      \
	bspline_phi_h.pdf                   \
	bspline_psi_g.pdf                   \
	Snn_bspline.pdf                     \
	sinsin02.pdf                        \
	sinsin02_pun.pdf                    \
	sinsin02hn.pdf                      \
	rsin.pdf                            \
	rsin_pun.pdf                        \
	rsin02hn.pdf

GRP_SETOPS =                            \
	latsetops.pdf                       \
	setop_0000.pdf                      \
	setop_0001.pdf                      \
	setop_0010.pdf                      \
	setop_0011.pdf                      \
	setop_0100.pdf                      \
	setop_0101.pdf                      \
	setop_0110.pdf                      \
	setop_0111.pdf                      \
	setop_1000.pdf                      \
	setop_1001.pdf                      \
	setop_1010.pdf                      \
	setop_1011.pdf                      \
	setop_1100.pdf                      \
	setop_1101.pdf                      \
	setop_1110.pdf                      \
	setop_1111.pdf

#  standardsetops.pdf

GRP_SETSTR =                            \
	lat6_primo_ss_xyz.pdf               \
	lat5_m3_ss_xyz.pdf                  \
	latwavxyz.pdf                       \
	latlattopxyz.pdf                    \
	lattopxy.pdf                        \
	latlatalgwxyz.pdf                   \
	latlatringxyz.pdf                   \
	latlatpartitionsxyz.pdf             \
	latlatringxy.pdf                    \
	latlatalgxyz.pdf                    \
	latlatpartwxyz.pdf                  \
	latlattopxyz_covers.pdf

GRP_SPLINE =                            \
	fstep.pdf                           \
	tent_pun.pdf                        \
	n0.pdf                              \
	n1.pdf                              \
	n2.pdf                              \
	n3.pdf                              \
	n3x.pdf                             \
	n4.pdf                              \
	n5.pdf                              \
	n6.pdf                              \
	n7.pdf                              \
	b0_g.pdf                            \
	b1_g.pdf                            \
	b2_g.pdf                            \
	n0_h.pdf                            \
	n1_h.pdf                            \
	n2_h.pdf                            \
	n3_h.pdf                            \
	n4_h.pdf                            \
	n0punity.pdf                        \
	n1punity.pdf                        \
	n2punity.pdf                        \
	n0dyadic.pdf                        \
	n1dyadic.pdf                        \
	n2dyadic.pdf                        \
	pulse_pun.pdf                       \
	Fpulse.pdf                          \
	tent012.pdf                         \
	tent_pun.pdf                        \
	Ftent012.pdf                        \
	FN2.pdf                             \
	cencubs.pdf                         \
	cencubs_pun.pdf

GRP_SYSTEM =                            \
	sysH_xy.pdf                         \
	sysHw_xy.pdf                        \
	sysHz_xy.pdf                        \
	sysH_cnoise.pdf                     \
	sysH_xy0v-q.pdf                     \
	sysH_xyuv--.pdf                     \
	sysH_xy0v--.pdf                     \
	sysH_xyu0--.pdf                     \
	sysH_xyvq.pdf                       \
	sysH_xyup.pdf                       \
	sysH_xypw.pdf                       \
	sysH_estH.pdf                       \
	sysT_xyvq.pdf                       \
	sysT_xyup.pdf                       \
	sysT_xypw.pdf                       \
	sys_xvy.pdf                         \
	transferHs_p.pdf                    \
	transferHs_ddp.pdf                  \
	xGy_xHw.pdf                         \
	xGy_xHw_addnoise.pdf                \
	xTy_xHw.pdf                         \
	opH_cnoise.pdf                      \
	opH_mnoise.pdf                      \
	opT_cnoise.pdf                      \
	opT_mnoise.pdf                      \
	opT_opH_cnoise.pdf                  \
	opT_opH_mnoise.pdf                  \
	opT_estH_cnoise.pdf                 \
	opT_estH_mnoise.pdf                 \
	opT_estG_estH_mnoise.pdf            \
	opT_estG_estH_cnoise.pdf            \
	dual_addnoise.pdf                   \
	sysH_mnoise.pdf

GRP_TOPOLOGY =                          \
	cont_ydy.pdf                        \
	cont_yfy.pdf                        \
	cont_yx.pdf                         \
	lat5_m3_nontop.pdf                  \
	lat5_n5_nontop.pdf                  \
	lat5_l2onm2_top.pdf                 \
	lat5_m2onl2_top.pdf                 \
	lat5_l5_top.pdf                     \
	lat2xyzdotted.pdf                   \
	lattopxyz.pdf                       \
	butterfly_setA.pdf                  \
	butterfly_clsA.pdf                  \
	butterfly_intA.pdf                  \
	butterfly_bndA.pdf                  \
	butterfly_drvA.pdf

GRP_VENN =                              \
	venn_emptyset.pdf                   \
	venn_cmpA.pdf                       \
	venn_setdiff.pdf                    \
	venn_cmpB.pdf                       \
	venn_symdiff.pdf                    \
	venn_intersect.pdf                  \
	venn_union.pdf                      \
	venn_universal.pdf

#  2p2roots.pdf          \

FILE_WAV =                              \
	bspline_pz.pdf                      \
	D1_pz.pdf                           \
	D2_pz.pdf                           \
	D3_pz.pdf                           \
	D4_pz.pdf                           \
	D8_pz.pdf                           \
	D12_pz.pdf                          \
	D16_pz.pdf                          \
	S4_pz.pdf                           \
	S5_pz.pdf                           \
	S6_pz.pdf                           \
	S7_pz.pdf                           \
	S8_pz.pdf                           \
	S9_pz.pdf                           \
	S10_pz.pdf                          \
	S11_pz.pdf                          \
	S12_pz.pdf                          \
	S13_pz.pdf                          \
	S14_pz.pdf                          \
	S15_pz.pdf                          \
	S16_pz.pdf                          \
	S17_pz.pdf                          \
	d1_g.pdf                            \
	d1_h.pdf                            \
	d1_phi.pdf                          \
	d1_psi.pdf                          \
	d1_phi_h.pdf                        \
	d1_psi_g.pdf                        \
	d2_phi_h.pdf                        \
	d2_psi_g.pdf                        \
	d3_phi_h.pdf                        \
	d3_psi_g.pdf                        \
	d4_phi_h.pdf                        \
	d4_psi_g.pdf                        \
	d5_phi_h.pdf                        \
	d5_psi_g.pdf                        \
	d6_phi_h.pdf                        \
	d6_psi_g.pdf                        \
	d7_phi_h.pdf                        \
	d7_psi_g.pdf                        \
	d8_phi_h.pdf                        \
	d8_psi_g.pdf                        \
	d9_phi_h.pdf                        \
	d9_psi_g.pdf                        \
	d10_phi_h.pdf                       \
	d10_psi_g.pdf                       \
	d11_phi_h.pdf                       \
	d11_psi_g.pdf                       \
	d12_phi_h.pdf                       \
	d12_psi_g.pdf                       \
	d16_phi_h.pdf                       \
	d16_psi_g.pdf                       \
	Dp_pz.pdf                           \
	mexhatwavelet.pdf                   \
	morletwavelet.pdf                   \
	s4_psi_g.pdf                        \
	s8_phi_h.pdf                        \
	s8_psi_g.pdf                        \
	s12_phi_h.pdf                       \
	s12_psi_g.pdf                       \
	s16_phi_h.pdf                       \
	s16_psi_g.pdf                       \

#  venn_ABc.pdf               \
#  venn_AB.pdf                \
#  venn_AcB.pdf
#  venn_AcBc.pdf

FILE_STY  =                             \
	../../common/sty/wavelets.sty       \
	../../common/sty/math.sty           \
	../../common/sty/dan.sty            \
	../../common/sty/defaults.sty       \
	../../common/sty/fonts.sty          \
	../../common/sty/packages.sty       \
	../../common/sty/xsd.sty            \
	../../common/sty/language.sty

#--------------------------------------
# Programs
#--------------------------------------
PRG_TYPESET = xelatex.exe

#--------------------------------------
# master build control $(FILE_CC)
#--------------------------------------
top: $(FILE_GRP) $(GRP_BOOLEAN) $(GRP_BASIS) $(BSPLINES) $(GRP_MATH) $(GRP_DATA) $(GRP_DICE) $(GRP_DSP) $(GRP_FRAMES) \
	$(GRP_FUZZY) $(GRP_LARC) $(GRP_LAT) $(GRP_LATU) $(GRP_LATP) $(GRP_LATOC) $(GRP_LOGIC) $(GRP_NEG) \
	$(GRP_NIL) $(OCS) $(OMS) $(GRP_OSET) $(GRP_PDS) $(GRP_POUNITY) $(GRP_PROB) $(GRP_SETOPS) $(GRP_SETSTR) $(GRP_SPLINE) \
	$(GRP_DNA) $(GRP_SYSTEM) $(GRP_TOPOLOGY) $(GRP_VENN) $(FILE_WAV)
	@echo Done ... graphics pdfs are ready!

#--------------------------------------
# implicit build control
#--------------------------------------
{$(PATHMATH)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHARGMIN)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHBALLS)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHDATA)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHDSP)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHBSPLINES)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

%.pdf : shell_%.tex
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHFRAME)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHOMS)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHPROB)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHVENN)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHSYSTEM)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHWAVE)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHCC)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHLAT)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHLATU)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHLATOC)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHMETRIC)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHNEG)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHOCS)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHOCSRV)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHLOGIC)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHFUZZY)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHSETOPS)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHSETSTR)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHOSETU)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHOSET)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHSTO)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHSYMSEQ)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

{$(PATHHISTORY)}.tex.pdf:
	$(PRG_TYPESET) shell_$&.tex
	copy /V/Y shell_$&.pdf $&.pdf
	del shell_$&.pdf

#--------------------------------------
# commands
#--------------------------------------
clean:
  del *.aux
  del *.log
  del *.out

#\hfill\tbox{r3_projection.pdf}

