%============================================================================
% Daniel J. Greenhoe
% references:
%   https://octave.org/doc/v4.2.1/Image-Processing.html
%   image: https://www.gentex.com/box/44?iframe=true&width=900&height=600
%          https://www.gentex.com/sites/default/files/imagecache/fire_product/GEC3_24WR.png
%============================================================================
image_rgb  = imread("GEC3_24WR.png");
image_gray = rgb2gray(image_rgb);
%filter1= [1];
%filter20= [1 -1; ...
%          0  0  ...
%         ]
%filter6= [ 1 -1  1 -1  1 -1; ...
%          -1  1 -1  1 -1  1; ...
%           1 -1  1 -1  1 -1; ...
%          -1  1 -1  1 -1  1; ...
%           1 -1  1 -1  1 -1; ...
%          -1  1 -1  1 -1  1; ...
%         ]
%filter60=[ 1 -1  1 -1  1 -1; ...
%           0  0  0  0  0  0; ...
%           0  0  0  0  0  0; ...
%           0  0  0  0  0  0; ...
%           0  0  0  0  0  0; ...
%           0  0  0  0  0  0; ...
%         ]
a  =  (1-sqrt(3))/4; 
b  = -(3-sqrt(3))/4; 
c  =  (3+sqrt(3))/4;
d  = -(1+sqrt(3))/4;
d4 = [a,b,c,d; ...
      b,0,0,0; ...
      c,0,0,0; ...
      d,0,0,0  ...
     ];
image_new = conv2(image_gray, d44, "same");
minval    = min(min(image_new));
image_new = image_new + abs(minval);
maxval    = max(max(image_new));
image_new = image_new / maxval;
image_new = ones(200,200)-image_new;
%size(image_new)
%min(min(image_new))
%max(max(image_new))
%imwrite(image_rgb,"image_rgb.jpg");
%imwrite(image_gray,"image_gray.jpg");
imwrite(image_new,"image_new.png");
%[Dx, Dy]   = gradient (image_new);